// SPDX-FileCopyrightText: 2026 Josef Gallmetzer
//
// SPDX-License-Identifier: MPL-2.0

//go:build ignore

// Command generate-traffic-zone-points derives the traffic zone reference table
// in internal/commands/traffic_zone_points.go from the live Mobility Timeseries
// event feed.
//
// PROVINCE_BZ Timeseries event rows carry both a messageZoneId and a point
// geometry; Content API Announcement records carry the point but no zone. The
// table lets --source content infer a zone by nearest reference point.
//
// The output is committed, not generated at build time. Rerun it when the
// historical window or the zone list changes:
//
//	go run scripts/generate-traffic-zone-points.go \
//	  -from 2024-01-01 -to 2025-12-31 \
//	  -out internal/commands/traffic_zone_points.go
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// coordinatePrecision is the number of decimal places grid cells are rounded to.
// Three places is roughly 110 m of latitude, which collapses repeated notices at
// the same spot without merging neighbouring roads.
const coordinatePrecision = 3

type eventRow struct {
	Metadata struct {
		ZoneID any `json:"messageZoneId"`
	} `json:"evmetadata"`
	Geometry struct {
		Coordinates []float64 `json:"coordinates"`
	} `json:"evlgeometry"`
}

type cell struct {
	lat float64
	lon float64
}

func main() {
	baseURL := flag.String("base-url", "https://mobility.api.opendatahub.com", "Mobility API base URL")
	from := flag.String("from", "2024-01-01", "start date YYYY-MM-DD")
	to := flag.String("to", "2025-12-31", "end date YYYY-MM-DD")
	limit := flag.Int("limit", 20000, "maximum rows to request")
	out := flag.String("out", "internal/commands/traffic_zone_points.go", "output Go file")
	flag.Parse()

	requestURL := fmt.Sprintf("%s/v2/flat,event/PROVINCE_BZ/%s/%s?limit=%d", strings.TrimSuffix(*baseURL, "/"), *from, *to, *limit)
	rows, err := fetch(requestURL)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}

	zonesByCell := map[cell]map[string]struct{}{}
	usable := 0
	for _, row := range rows {
		zoneID := zoneIDString(row.Metadata.ZoneID)
		if zoneID == "" || len(row.Geometry.Coordinates) < 2 {
			continue
		}
		usable++
		key := cell{
			lat: round(row.Geometry.Coordinates[1], coordinatePrecision),
			lon: round(row.Geometry.Coordinates[0], coordinatePrecision),
		}
		if zonesByCell[key] == nil {
			zonesByCell[key] = map[string]struct{}{}
		}
		zonesByCell[key][zoneID] = struct{}{}
	}

	type point struct {
		cell
		zoneID string
	}
	points := make([]point, 0, len(zonesByCell))
	contested := 0
	for key, zones := range zonesByCell {
		// A cell claimed by more than one zone cannot be resolved from this data,
		// and guessing one would silently misplace announcements near it.
		if len(zones) != 1 {
			contested++
			continue
		}
		for zoneID := range zones {
			points = append(points, point{cell: key, zoneID: zoneID})
		}
	}
	sort.Slice(points, func(i, j int) bool {
		if points[i].lat != points[j].lat {
			return points[i].lat < points[j].lat
		}
		if points[i].lon != points[j].lon {
			return points[i].lon < points[j].lon
		}
		return points[i].zoneID < points[j].zoneID
	})

	perZone := map[string]int{}
	for _, p := range points {
		perZone[p.zoneID]++
	}
	zoneIDs := make([]string, 0, len(perZone))
	for zoneID := range perZone {
		zoneIDs = append(zoneIDs, zoneID)
	}
	sort.Strings(zoneIDs)
	counts := make([]string, 0, len(zoneIDs))
	for _, zoneID := range zoneIDs {
		counts = append(counts, fmt.Sprintf("zone %s: %d", zoneID, perZone[zoneID]))
	}

	var buf strings.Builder
	buf.WriteString("// SPDX-FileCopyrightText: 2026 Josef Gallmetzer\n")
	buf.WriteString("//\n")
	buf.WriteString("// SPDX-License-Identifier: MPL-2.0\n\n")
	buf.WriteString("// Code generated by scripts/generate-traffic-zone-points.go. DO NOT EDIT.\n\n")
	buf.WriteString("package commands\n\n")
	buf.WriteString(comment(fmt.Sprintf(
		"trafficZonePoints maps a rounded coordinate to the PROVINCE_BZ zone observed there, derived from the %d Mobility Timeseries event rows for %s..%s that carry both a messageZoneId and a point geometry. Coordinates are rounded to %d decimal places and deduplicated; %d cells were claimed by more than one zone and are absent rather than assigned. Per zone: %s.",
		usable, *from, *to, coordinatePrecision, contested, strings.Join(counts, ", "))))
	fmt.Fprintf(&buf, "var trafficZonePoints = []trafficZonePoint{\n")
	for _, p := range points {
		fmt.Fprintf(&buf, "\t{%.*f, %.*f, %q},\n", coordinatePrecision, p.lat, coordinatePrecision, p.lon, p.zoneID)
	}
	buf.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(buf.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "%s: %d rows, %d cells, %d contested cells dropped, %d reference points (%s)\n",
		*out, usable, len(zonesByCell), contested, len(points), strings.Join(counts, ", "))
	fmt.Fprintln(os.Stderr, "run gofmt on the output before committing")
}

// comment wraps text into a Go line comment block at a readable width.
func comment(text string) string {
	const width = 74
	var out strings.Builder
	line := "//"
	for _, word := range strings.Fields(text) {
		if len(line)+1+len(word) > width {
			out.WriteString(line + "\n")
			line = "//"
		}
		line += " " + word
	}
	out.WriteString(line + "\n")
	return out.String()
}

func fetch(requestURL string) ([]eventRow, error) {
	client := &http.Client{Timeout: 5 * time.Minute}
	response, err := client.Get(requestURL)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", requestURL, response.Status)
	}
	var payload struct {
		Data []eventRow `json:"data"`
	}
	if err := json.NewDecoder(response.Body).Decode(&payload); err != nil {
		return nil, err
	}
	if len(payload.Data) == 0 {
		return nil, fmt.Errorf("GET %s returned no rows", requestURL)
	}
	return payload.Data, nil
}

// zoneIDString accepts the JSON number the feed sends today without assuming it
// stays a number.
func zoneIDString(value any) string {
	switch typed := value.(type) {
	case nil:
		return ""
	case string:
		return strings.TrimSpace(typed)
	case float64:
		return fmt.Sprintf("%d", int64(typed))
	default:
		return strings.TrimSpace(fmt.Sprint(typed))
	}
}

func round(value float64, places int) float64 {
	parsed, err := json.Number(fmt.Sprintf("%.*f", places, value)).Float64()
	if err != nil {
		return value
	}
	return parsed
}
